#!/bin/bash

##
# see https://docs.docker.com/docker-hub/builds/advanced/
#
# SOURCE_BRANCH: the name of the branch or the tag that is currently being tested.
# SOURCE_COMMIT: the SHA1 hash of the commit being tested.
# COMMIT_MSG: the message from the commit being tested and built.
# DOCKER_REPO: the name of the Docker repository being built.
# DOCKERFILE_PATH: the dockerfile currently being built.
# DOCKER_TAG: the Docker repository tag being built.
# IMAGE_NAME: the name and tag of the Docker repository being built.
# (This variable is a combination of  DOCKER_REPO:DOCKER_TAG.)

# our docker tags are e.g. "node6-sass2.2.0"
# SASS_VERSION ARG is something like "2.2.0" or "3.1.0"

docker build --build-arg SASS_VERSION="${DOCKER_TAG#node6-sass}" \
  -t $IMAGE_NAME .
